package org.river.exertion.ai.messaging

enum class MessageChannel {

    ECS_S2D_BRIDGE,
    S2D_ECS_BRIDGE,
    ECS_FSM_BRIDGE,
    PLAN_BRIDGE,
    PERCEPTION_BRIDGE,
    FEELING_BRIDGE,
    CURNODE_BRIDGE,
    NODEROOMMESH_BRIDGE,
    LOSMAP_BRIDGE,
    EXT_PHENOMENA,
    INT_PHENOMENA,
    INT_CONDITION,
    INT_FACET,
    INT_MEMORY,
    INT_PRESENT_SYMBOL_MODIFY,
    INT_PRESENT_SYMBOL_MODIFY_ALL,
    INT_PRESENT_SYMBOL_MODIFIED,
    INT_ABSENT_SYMBOL_MODIFY,
    INT_PRESENT_SYMBOL_SPAWN,
    INT_PRESENT_SYMBOL_DESPAWN,
    INT_ABSENT_SYMBOL_SPAWN,
    INT_ABSENT_SYMBOL_DESPAWN,
    INT_FOCUS,
    INT_PHENOMENA_FACETS,
    INT_MEMORY_FACETS
    ;

    fun id() = this.ordinal
}