package org.river.exertion.ai.messaging

enum class MessageChannel {

    ECS_S2D_BRIDGE,
    S2D_ECS_BRIDGE,
    ECS_FSM_BRIDGE,
    PLAN_BRIDGE,
    PERCEPTION_BRIDGE,
    FEELING_BRIDGE,
    UI_TIMING_DISPLAY,
    UI_FOCUS_DISPLAY,
    UI_FACET_DISPLAY,
    UI_SYMBOL_DISPLAY,
    UI_ANXIETY_BAR,
    CURNODE_BRIDGE,
    NODEROOMMESH_BRIDGE,
    LOSMAP_BRIDGE,
    EXT_PHENOMENA,
    INT_PHENOMENA,
    INT_CONDITION,
    INT_FACET,
    INT_MEMORY,
    INT_SYMBOL_MODIFY,
    INT_SYMBOL_MODIFIED,
    INT_SYMBOL_SPAWN,
    INT_SYMBOL_DESPAWN,
    INT_ADD_FOCUS_PLAN,
    INT_REMOVE_FOCUS_PLAN,
    INT_ADD_FOCUS_CHAIN_LINK,
    INT_REMOVE_FOCUS_CHAIN_LINK,
    INT_PHENOMENA_FACETS,
    INT_MEMORY_FACETS,
    INT_FACET_MODIFY,
    ;

    fun id() = this.ordinal
}